<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<style>
			.outer-box {
			width: 750px;
			margin: 12px;
			border: 2px solid #000000;
			background-color: #ffffff;
			color: #000000;
			display: flex;
			flex-direction: column;
			justify-content: flex-start;
			align-items: center;
			}

			.header {
			width: 100%;
			display: flex;
			flex-direction: column;
			justify-content: flex-start;
			align-items: center;
			border-bottom: 2px solid #000000;
			}

			.school-details {
			display: flex;
			flex-direction: row;
			justify-content: flex-start;
			}

			.school-logo {
			width: 10%;
			padding: 10px;
			}

			.school-title {
			width: 90%;
			flex-grow: 1;
			text-align: center;
			display: flex;
			flex-direction: column;
			}

			.school-name {
			font-size: 20px;
			margin: 0px;
			margin-top: 10px;
			}

			.school-balance {
			margin: 0px;
			margin-bottom: 6px;
			font-size: 12px;
			font-weight: bold;
			}

			h5 {
			margin: 0px;
			margin-top: 8px;
			margin-bottom: 3px;
			}

			h4 {
			margin: 0px;
			margin-top: 3px;
			margin-bottom: 8px;
			}

			.student-master {
			width: 100%;
			display: flex;
			flex-direction: column;
			}

			.sm-row {
			width: 100%;
			display: flex;
			flex-direction: row;
			}

			.sm-cell1 {
			width: 20%;
			margin: 4px;
			font-size: 12px;
			font-weight: bold;
			}
			.sm-cell2 {
			width: 30%;
			margin: 4px;
			font-size: 12px;
			font-weight: bold;
			}

			.table {
			width: 100%;
			border: 2px solid black;
			border-left: none;
			border-right: none;
			border-collapse: collapse;
			padding: 0px;
			font-size: 12px;
			}

			.hr {
			width: 100%;
			border-bottom: 2px solid black;
			border-collapse: collapse;
			}

			.sub {
			width: 12.5%;
			border: none;
			border-right: 2px solid black;
			border-collapse: collapse;
			margin: 0px;
			}

			.terms {
			width: 31.25%;
			border: 2px solid black;
			border-collapse: collapse;
			}

			.full {
				width: 25%;
				border: 2px solid black;
				border-collapse: collapse;
			}

			tr,th,td{
				border: 2px solid black;
				text-align: center;
			}

		</style>
		<script>
			function displayInfo(progressList) {

				const studentInfo = progressList.lstStudentInfo[0]
				const stGrades = progressList.stGrades

				let schoolNameEl = document.getElementById('schoolName');
				schoolNameEl.textContent = studentInfo.SchoolName;

				let schoolAddressEl = document.getElementById('schoolAddress');
				schoolAddressEl.textContent = studentInfo.SchoolAddress +', Ph. : '+studentInfo.SchoolPhoneNumber;

				let schoolEmailEl = document.getElementById('schoolEmail');
				schoolEmailEl.textContent = 'Visit Us at: '+studentInfo.SchoolEmail;

				let scholarNoEl = document.getElementById('scholarNo');
				scholarNoEl.textContent = ':- '+studentInfo.AdmissionNumber;

				let classEl = document.getElementById('class');
				classEl.textContent = ':- '+studentInfo.ClassName;

				let rollNoEl = document.getElementById('rollNo');
				rollNoEl.textContent = ':- '+studentInfo.RollNumber;

				let nameEl = document.getElementById('name');
				nameEl.textContent = ':- '+studentInfo.Name;

				let fatherNameEl = document.getElementById('fatherName');
				fatherNameEl.textContent = ':- '+studentInfo.FatherName;

				let motherNameEl = document.getElementById('motherName');
				motherNameEl.textContent = ':- '+studentInfo.MotherName;	

				let attendanceEl = document.getElementById('attendance');
				attendanceEl.textContent = ':- '+0;

				let dobEl = document.getElementById('dob');
				dobEl.textContent = ':- '+studentInfo.DOB;

				
				let internalsDetails = studentInfo.stInternals
				let subjectNames = []
				for (let each of internalsDetails) {
					if (each.ClassSubject in subjectNames) {
						pass
					} else {
						subjectNames.push(each.ClassSubject)
					}
				};

				const subjects = new Set(subjectNames)
				console.log(subjects)

				const firstTermInternals = []
				const secondTermInternals = []
				for (let subject of subjects) {
					let filteredInternals = internalsDetails.filter(each => each.ClassSubject===subject)
					firstTermInternals.push(Math.max(parseInt(filteredInternals[0].GradePoints),parseInt(filteredInternals[1].GradePoints)))
					secondTermInternals.push(Math.max(parseInt(filteredInternals[2].GradePoints),parseInt(filteredInternals[3].GradePoints)))
				}
				console.log(firstTermInternals, secondTermInternals)

				const termDetails = studentInfo.lstStudent
				const firstTermMains = []
				const secondTermMains = []
				for (let subject of subjects) {
					let filteredMains = termDetails.filter(each => each.SubjectName===subject)
					firstTermMains.push(parseInt(filteredMains[0].Subject_GradePoints))
					secondTermMains.push(parseInt(filteredMains[1].Subject_GradePoints))
				}
				console.log(firstTermMains, secondTermMains)

				const firstTermTotal = []
				for (let i in firstTermInternals) {
					firstTermTotal.push(0.2*firstTermInternals[i]+0.8*firstTermMains[i])
				}

				const secondTermTotal = []
				for (let i in secondTermInternals) {
					secondTermTotal.push(0.2*secondTermInternals[i]+0.8*secondTermMains[i])
				}

				const finalResult = []
				for (let i in firstTermTotal) {
					finalResult.push(0.5*firstTermTotal[i]+0.5*secondTermTotal[i])
				}

				const grades = []
				for (let score of finalResult) {
					for (let grade of stGrades) {
						if (grade.minRange <= score*10 <= grade.maxRange) {
							grades.push(grade.Grade.trim())
							break
						}
					}
				}

				console.log(grades)


				for (let i in subjects) {
					let tableEl = document.getElementById("table");

					let rowEl = document.createElement("tr")

					let subjectEl = document.createElement("th")
					subjectEl.textContent = subjects[i]
					rowEl.appendChild(subjectEl)

					let internal1El = document.createElement("td")
					internal1El.textContent = firstTermInternals[i]
					rowEl.appendChild(internal1El)

					let mains1El = document.createElement("td")
					mains1El.textContent = firstTermMains[i]
					rowEl.appendChild(mains1El)

					let total1El = document.createElement("td")
					total1El.textContent = firstTermTotal[i]
					rowEl.appendChild(total1El)

					let internal2El = document.createElement("td")
					internal2El.textContent = secondTermInternals[i]
					rowEl.appendChild(internal2El)

					let mains2El = document.createElement("td")
					mains2El.textContent = secondTermMains[i]
					rowEl.appendChild(mains2El)

					let total2El = document.createElement("td")
					total2El.textContent = secondTermTotal[i]
					rowEl.appendChild(total2El)

					let grandTotal = document.createElement("td")
					grandTotal.textContent = finalResult[i]
					rowEl.appendChild(grandTotal)

					let gradeEl = document.createElement("td")
					gradeEl.textContent = grades[i]
					rowEl.appendChild(gradeEl)

					tableEl.appendChild(rowEl)
				}



			}

			let url = "http://stageapi.iguru.guru:222/api/ExamManagement/GetStudentProgressReports?schoolID=282&sectionID=2682&eXamMasID=8442&students=181521";
            let options = {
    		  method: "GET"
    		};
    		fetch(url, options)
    		  .then(function (response) {
    		    return response.json();
    		  })
    		  .then(function (jsonData) {
				let progressList = jsonData.Response.ProgressList;
				displayInfo(progressList)
    		  });

			
		</script>
		<title>Hardware Diagnostics Log</title>
	</head>
	<body>
		<div class="outer-box">
			<div class="header">
			  <div class="school-details">
				<img
				  src="https://ik.imagekit.io/sps1un6dc/iGuru/iGuru_Logo.jpg?updatedAt=1680254864475"
				  alt="school_logo"
				  class="school-logo"
				/>
				<div class="school-title">
				  <h1 class="school-name" id="schoolName"></h1>
				  <p class="school-balance" id="schoolAddress"></p>
				  <p class="school-balance" id="schoolEmail"></p>
				</div>
			  </div>
			  <h5>REPORT CARD</h5>
			  <h4>ACADEMIC SESSION: 2022-23</h4>
			</div>
			<div class="student-master">
			  <div class="sm-row">
				<p class="sm-cell1">Scholar No</p>
				<p class="sm-cell2" id="scholarNo"></p>
				<p class="sm-cell1">Class</p>
				<p class="sm-cell2" id="class"></p>
			  </div>
			  <div class="sm-row">
				<p class="sm-cell1">Roll No</p>
				<p class="sm-cell2" id="rollNo"></p>
				<p class="sm-cell1">Name of Student</p>
				<p class="sm-cell2" id="name"></p>
			  </div>
			  <div class="sm-row">
				<p class="sm-cell1">Father's Name</p>
				<p class="sm-cell2" id="fatherName"></p>
				<p class="sm-cell1">Mother's Name</p>
				<p class="sm-cell2" id="motherName"></p>
			  </div>
			  <div class="sm-row">
				<p class="sm-cell1">Attendance</p>
				<p class="sm-cell2" id="attendance"></p>
				<p class="sm-cell1">Date of Birth</p>
				<p class="sm-cell2" id="dob"></p>
			  </div>
			</div>

			<table class="table" id="table">
				<tr class="hr">
					<th class="sub" rowspan="2" >Subjects</th>
					<th class="terms" colspan="3">Term 1</th>
					<th class="terms" colspan="3">Term 2</th>
					<th class="full" colspan="2">Final Result</th>
				</tr>
	
				<tr>
					<th>Best Score PT-I,II</br>20</th>
					<th>Term I</br>80</th>
					<th>Marks Obt.</br>100</th>
	
					<th>Best Score PT-I,II</br>20</th>
					<th>Term I</br>80</th>
					<th>Marks Obt.</br>100</th>
	
					<th>T-I + T-II</br>200</th>
					<th>Grade</th>
				</tr>
	
				<tr>
					<th>ENGLISH</th>
					
					<td>15</td>
					<td>15</td>
					<td>15</td>
	
					<td>15</td>
					<td>15</td>
					<td>15</td>
	
					<td>15</td>
					<td>15</td>
				</tr>

			</table>

		</div>
	</body>
</html>
